MVCFilmSon/Controllers/FilmYonetController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCFilmSon.Models;

namespace MVCFilmSon.Controllers
{
    [Authorize(Roles = "Admin")] //Buraya yazarak classın içindekiler dahil
    public class FilmYonetController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: FilmYonet
        //[Authorize(Roles ="Admin")] --> Buraya yazarsak her meotodun üzerine yazmamız gerekir.
        //[AllowAnonymous] --> Classı sadece admine açtık. Ama bazı metodları herkese açık hale getirebiliriz. 
        public ActionResult Index()
        {
            var filmler = db.Filmler.Include(f => f.FilminKategorisi);
            return View(filmler.ToList());
        }

        // GET: FilmYonet/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Film film = db.Filmler.Find(id);
            if (film == null)
            {
                return HttpNotFound();
            }
            return View(film);
        }

        // GET: FilmYonet/Create
        public ActionResult Create()
        {
            ViewBag.KategoriID = new SelectList(db.Kategoriler, "KategoriID", "KategoriAdi");
            return View();
        }

        // POST: FilmYonet/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FilmID,FilmAdi,Yonetmen,Konu,KategoriID,ResimURL,Fragman,Yabanci,Yil")] Film film, HttpPostedFileBase ResimURL)
        {
            if (ModelState.IsValid) /*Kullanıcı modeler uygun veri girişi yaptıysa*/
            {
                if (ResimURL.ContentLength > 0)
                    ResimURL.SaveAs(Server.MapPath("/Content/filmresim/")+ResimURL.FileName);

                film.ResimURL = ResimURL.FileName;

                var yid = film.Fragman.Split('=').Last(); //Last() dizideki sondaki elemanı alır.

                string sonuc = string.Format("<iframe width='560' height='315' src='https://www.youtube.com/embed/{0}' frameborder='0' allowfullscreen></iframe>",yid);

                film.Fragman = sonuc;

                db.Filmler.Add(film);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.KategoriID = new SelectList(db.Kategoriler, "KategoriID", "KategoriAdi", film.KategoriID);
            return View(film);
        }

        // GET: FilmYonet/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Film film = db.Filmler.Find(id);
            if (film == null)
            {
                return HttpNotFound();
            }
            ViewBag.KategoriID = new SelectList(db.Kategoriler, "KategoriID", "KategoriAdi", film.KategoriID);
            return View(film);
        }

        // POST: FilmYonet/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)] //HTML kodları iletebilmek için. <iframe> gibi
        public ActionResult Edit([Bind(Include = "FilmID,FilmAdi,Yonetmen,Konu,KategoriID,ResimURL,Fragman,Yabanci,Yil")] Film film)
        {
            if (ModelState.IsValid)
            {
                db.Entry(film).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.KategoriID = new SelectList(db.Kategoriler, "KategoriID", "KategoriAdi", film.KategoriID);
            return View(film);
        }

        // GET: FilmYonet/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Film film = db.Filmler.Find(id);
            if (film == null)
            {
                return HttpNotFound();
            }
            return View(film);
        }

        // POST: FilmYonet/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Film film = db.Filmler.Find(id);
            db.Filmler.Remove(film);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCFilmSon/Views/FilmYonet/Create.cshtml
@model MVCFilmSon.Models.Film

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@*<form enctype="multipart/form-data"></form> //Aşğıdaki using ile aynı*@
@using (Html.BeginForm("Create", "FilmYonet", FormMethod.Post, new { @enctype = "multipart/form-data", @class = "bizimclass" })) //@ işareti ile istediğimiz kadar attribute koyabiliriz.
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Film</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FilmAdi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FilmAdi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FilmAdi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Yonetmen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Yonetmen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Yonetmen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Konu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Konu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Konu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KategoriID, "KategoriID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("KategoriID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.KategoriID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group"> @*modelden kasıt en yukarıda tanımlanan model. Sadece bir tane tanımlanabilir.*@
            @Html.LabelFor(model => model.ResimURL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ResimURL, new { htmlAttributes = new { @class = "form-control", @type = "file" } })
                @Html.ValidationMessageFor(model => model.ResimURL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fragman, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fragman, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fragman, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Yabanci, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Yabanci)
                    @Html.ValidationMessageFor(model => model.Yabanci, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Yil, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">                
                    @Html.EditorFor(model => model.Yil)
                    @Html.ValidationMessageFor(model => model.Yil, "", new { @class = "text-danger" })           
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCFilmSon/Views/FilmYonet/Delete.cshtml
@model MVCFilmSon.Models.Film

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Film</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FilminKategorisi.KategoriAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FilminKategorisi.KategoriAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FilmAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FilmAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Yonetmen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Yonetmen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Konu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Konu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ResimURL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ResimURL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fragman)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fragman)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Yabanci)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Yabanci)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVCFilmSon/Views/FilmYonet/Details.cshtml
@model MVCFilmSon.Models.Film

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Film</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FilminKategorisi.KategoriAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FilminKategorisi.KategoriAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FilmAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FilmAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Yonetmen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Yonetmen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Konu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Konu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ResimURL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ResimURL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fragman)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fragman)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Yabanci)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Yabanci)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.FilmID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVCFilmSon/Views/FilmYonet/Edit.cshtml
@model MVCFilmSon.Models.Film

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Film</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.FilmID)

        <div class="form-group">
            @Html.LabelFor(model => model.FilmAdi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FilmAdi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FilmAdi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Yonetmen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Yonetmen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Yonetmen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Konu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Konu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Konu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KategoriID, "KategoriID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("KategoriID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.KategoriID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ResimURL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ResimURL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ResimURL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fragman, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fragman, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fragman, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Yabanci, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Yabanci)
                    @Html.ValidationMessageFor(model => model.Yabanci, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Yil, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    @Html.EditorFor(model => model.Yil)
                    @Html.ValidationMessageFor(model => model.Yil, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCFilmSon/Views/FilmYonet/Index.cshtml
@model IEnumerable<MVCFilmSon.Models.Film>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FilminKategorisi.KategoriAdi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FilmAdi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Yonetmen)
        </th>

        @*<th>
            @Html.DisplayNameFor(model => model.Konu)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ResimURL)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fragman)
        </th>*@

        <th>
            @Html.DisplayNameFor(model => model.Yabanci)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FilminKategorisi.KategoriAdi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FilmAdi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Yonetmen)
        </td>

        @*<td>
            @Html.DisplayFor(modelItem => item.Konu)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ResimURL)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fragman)
        </td>*@

        <td>
            @*@Html.DisplayFor(modelItem => item.Yabanci)  // Sildik.*@

            @Html.Raw(item.Yabanci ? "Yabancı" : "Yerli") @*Birşey yazmak için paranteze al.*@
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.FilmID }) |
            @Html.ActionLink("Details", "Details", new { id=item.FilmID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.FilmID })
        </td>
    </tr>
}

</table>